### PR TITLE
Fix commentbox height issue in responsive and normal view

### PR DESCRIPTION
**Pull request by malavvasita**
Issue ref: #884 

Enhancement:
Don't need to fix height of comment box.

Increase height of comment box on adding comments only.

### CODE REVIEW

**Comment by kapilpaul** [comment]
@pooja-muchandikar please test this PR

**Comment by pooja-muchandikar** [comment]
@kapilpaul 

As per this https://github.com/rtCamp/rtMedia/issues/884#issuecomment-428072539 looks like this issue is fixed in v4.8.8. Then what changes are there in this PR?

Auto scroll in comments is working as expected.

**Comment by kapilpaul** [comment]
@pooja-muchandikar this PR is not for autoscrolling. This is for comment box height issue in responsive and normal view.

**Comment by pooja-muchandikar** [comment]
@kapilpaul 

Cross-checked in responsive device and the changes added in this PR are reflecting please merge the PR

**Pull request merged**
