### PR TITLE
Change addon page design

### PR DESCRIPTION
**Pull request by sabbir1991**

### CODE REVIEW

**Review by kamalahmed — APPROVED** [review]
looks okey

**Comment by thebengalboy** [comment]
@pavanpatil1 

Please could you have a quick check on this?

**Comment by pavanpatil1** [comment]
Hi @thebengalboy, Cross-checked the issue, Page looks good. Just notice one thing the Get `now button` is not working we have added the # links for all the buttons. So should we merge this after adding the links ?.

**Comment by thebengalboy** [comment]
Thank you @pavanpatil1 

I've added `on-hold` tag on this PR for now.

**Comment by thebengalboy** [comment]
@Pradeep1308 Please could you take this and update the PR by adding the following URL on the `Get it` button?

URL: `https://rtmedia.io/rtmedia-premium`

**Comment by Pradeep1308** [comment]
@pavanpatil1 please check this PR, updated with the url

**Comment by pavanpatil1** [comment]
Checked the New addon page, Links are working and redirecting to the premium page now. You can merge the PR @Pradeep1308. 


https://user-images.githubusercontent.com/44057535/159667310-fbec86de-3613-4332-a955-de326b2caa6b.mp4

**Pull request merged**
