### PR TITLE
GH-1738 : Fixed unsupported file issue

### PR DESCRIPTION
**Pull request by OpuRockey**
This PR is related to issue : https://github.com/rtCamp/rtMedia/issues/1738

### CODE REVIEW

**Review by kapilpaul — APPROVED** [review]

**Comment by pooja-muchandikar** [comment]
@OpuRockey 

On trying to add unsupported file keeping activity empty `&nbsp;` is shown in the activity text area. We shouldn't show this. I remember we had fixed this `&nbsp;` showing previously. Can we have some other workaround for this?
Screenshot 2021-09-14 at 11 31 21 PM

**Comment by OpuRockey** [comment]
> @OpuRockey
> 
> On trying to add unsupported file keeping activity empty `&nbsp;` is shown in the activity text area. We shouldn't show this. I remember we had fixed this `&nbsp;` showing previously. Can we have some other workaround for this?
> Screenshot 2021-09-14 at 11 31 21 PM

@pooja-muchandikar , I will check that & let you know.

**Comment by OpuRockey** [comment]
@pooja-muchandikar , Fixed that `&nbsp;` issue if trying to upload unsupported file. Please get it tested.

**Comment by pooja-muchandikar** [comment]
> https://github.com/rtCamp/rtMedia/pull/1741#issuecomment-919392883

This issue is been fixed.

**Pull request merged**
