### PR TITLE
fix: count media on delete

### PR DESCRIPTION
**Pull request by kapilpaul**
This PR will fix

Count media after delete a media file on user profile.

issue: #1548

### CODE REVIEW

**Comment by kapilpaul** [comment]
@pooja-muchandikar please test this PR

**Comment by pooja-muchandikar** [comment]
@kapilpaul 

Is this PR related to any previous PR? If yes can you mention the PR/issue link?

**Comment by kapilpaul** [comment]
@pooja-muchandikar this is the original [PR](https://github.com/rtCamp/rtMedia/pull/1556). 

issue: #1548

**Comment by pooja-muchandikar** [comment]
@kapilpaul 

Cross-checked this PR and the fix is working as expected. Please merge the PR.

**Pull request merged**
