### PR TITLE
fix typos and remove duplicate comment

### PR DESCRIPTION
**Pull request by akkspros**
fix typos and remove the duplicate comment

### CODE REVIEW

**Comment by SID177** [comment]
You deleted `RTMediaAdmin.php` file?

**Comment by akkspros** [comment]
@SID177 yes

**Comment by kapilpaul** [comment]
@akkspros Hi, can you please explain why you deleted the `RTMediaAdmin.php` file?

**Comment by kapilpaul** [comment]
as there is no reply from author created a new [PR](https://github.com/rtCamp/rtMedia/pull/1761) and closing this one.

**Pull request closed without merging**
