### PR TITLE
Add try catch and undefined check before checking action of ajax call

### PR DESCRIPTION
**Pull request by SID177**
- Add try catch and undefined check before checking action of ajax call
- To fix the conflict with EventON plugin, because for some ajax calls it doesn't pass `action` parameter

### CODE REVIEW

**Comment by pooja-muchandikar** [comment]
Tested `fix/conflict-eventon-plugin` branch and the fix added is not conflicting with edit activity.

**Review by vaishaliagola27 — APPROVED** [review]

**Comment by pooja-muchandikar** [comment]
Tested with `pre-release` branch and the fix added is not conflicting with edit activity.

**Comment by pooja-muchandikar** [comment]
Tested with `develop` branch and the fix added is not conflicting with edit activity.

**Comment by pooja-muchandikar** [comment]
Released with `v4.6.6`

**Pull request merged**
