### PR TITLE
Fixed console js issues on settings page

### PR DESCRIPTION
**Pull request by sabbir1991**

### CODE REVIEW

**Review by kamalahmed — APPROVED** [review]
looks ok

**Comment by thebengalboy** [comment]
@pavanpatil1  I think we can merge it. Please let us know.

**Comment by pavanpatil1** [comment]
Hi @thebengalboy, Cross-checked the issue, Fix is working fine. We can merge the PR. 

image

**Comment by thebengalboy** [comment]
@sabbir1991 We can merge this PR

**Comment by thebengalboy** [comment]
@Pradeep1308 Please could you merge it?

**Pull request merged**
