### PR TITLE
Update media count on deletion event

### PR DESCRIPTION
**Pull request by vermadarsh**
Added code to update the media count when media is deleted from the following locations:
1. User profile -> Media tab
2. Single group -> Media tab

### CODE REVIEW

**Comment by kapilpaul** [comment]
@vermadarsh Hi, please resolve the merge conflicts.

**Comment by kapilpaul** [comment]
@pooja-muchandikar Before test this PR please check if the issue is still exists with the latest codes. Please let me know

**Comment by pooja-muchandikar** [comment]
@kapilpaul 

Tested this issue on our demo site and on media uploading the count is not increasing need to explicitly reload the page to check the count. But on media deletion the count is decreasing but first time deletion need to reload the page and later it works. 

The above scenario is same for the changes done in `GH--1548` branch. So these changes we need to recheck once. 

Reference:https://watch.screencastify.com/v/0pf48FT8vwMjV7L28GBk

**Comment by kapilpaul** [comment]
created 2 separate PR for this. Hence closing this PR.

**Pull request closed without merging**
